# @package _group_
common:
  fp16: True
  log_format: json
  log_interval: 100
  tensorboard_logdir: /home/wangzhijun2/mix-phoneme-bert/data/tensorboard
  no_progress_bar: True
  
checkpoint:
  no_epoch_checkpoints: true

task:
  _name: mix_phoneme_masked_lm
  sample_break_mode: complete
  tokens_per_sample: 510
  mask_whole_words: True
  data: /home/u1190303311/mix-phoneme-bert-main/fairseq/examples/roberta/config/pretraining

criterion: mix_phoneme_masked_lm

dataset:
  batch_size: 16
  ignore_unused_valid_subsets: true
  skip_invalid_size_inputs_valid_test: True
  num_workers: 4

optimizer:
  _name: adam
  weight_decay: 0.01
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 10000

optimization:
  clip_norm: 0
  lr: [0.0005]
  max_update: 10000
  update_freq: [8]

model:
  _name: mix_phoneme_roberta
  max_positions: 512
  dropout: 0.1
  attention_dropout: 0.1
  encoder_embed_dim: 256
  encoder_ffn_embed_dim: 1024
  encoder_attention_heads: 8
  encoder_layers: 6
